import './globals.css';

export const metadata = {
  title: 'Kokibon',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
       <link
         href="https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz:wght@300;400;700&family=Overpass:wght@400;700&family=PT+Serif+Caption&display=swap"
         rel="stylesheet"
       />
     </head>
      <body>
        {children}
      </body>
    </html>
  );
}
